# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AnaformDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 610)
        Dialog.setStyleSheet("")
        self.imgBulunan = QtWidgets.QLabel(Dialog)
        self.imgBulunan.setGeometry(QtCore.QRect(520, 10, 466, 400))
        self.imgBulunan.setMinimumSize(QtCore.QSize(466, 400))
        self.imgBulunan.setFrameShape(QtWidgets.QFrame.Panel)
        self.imgBulunan.setText("")
        self.imgBulunan.setObjectName("imgBulunan")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 530, 981, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startCam = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/ocrclose.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startCam.setIcon(icon)
        self.startCam.setIconSize(QtCore.QSize(32, 32))
        self.startCam.setObjectName("startCam")
        self.horizontalLayout.addWidget(self.startCam)
        self.btnOtomatikDurdur = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/autoon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOtomatikDurdur.setIcon(icon1)
        self.btnOtomatikDurdur.setIconSize(QtCore.QSize(32, 32))
        self.btnOtomatikDurdur.setObjectName("btnOtomatikDurdur")
        self.horizontalLayout.addWidget(self.btnOtomatikDurdur)
        self.btnAsamalar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/asamagoster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAsamalar.setIcon(icon2)
        self.btnAsamalar.setIconSize(QtCore.QSize(32, 32))
        self.btnAsamalar.setObjectName("btnAsamalar")
        self.horizontalLayout.addWidget(self.btnAsamalar)
        self.btnAyarlar = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icons/ayarlar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAyarlar.setIcon(icon3)
        self.btnAyarlar.setIconSize(QtCore.QSize(32, 32))
        self.btnAyarlar.setObjectName("btnAyarlar")
        self.horizontalLayout.addWidget(self.btnAyarlar)
        self.btnKopyala = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icons/kopyala.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnKopyala.setIcon(icon4)
        self.btnKopyala.setIconSize(QtCore.QSize(32, 32))
        self.btnKopyala.setObjectName("btnKopyala")
        self.horizontalLayout.addWidget(self.btnKopyala)
        self.imgCamera_2 = QtWidgets.QLabel(Dialog)
        self.imgCamera_2.setGeometry(QtCore.QRect(20, 10, 466, 400))
        self.imgCamera_2.setMinimumSize(QtCore.QSize(466, 400))
        self.imgCamera_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.imgCamera_2.setText("")
        self.imgCamera_2.setObjectName("imgCamera_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 420, 971, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.vlCevaplar = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.vlCevaplar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.vlCevaplar.setContentsMargins(10, 0, 10, 0)
        self.vlCevaplar.setSpacing(5)
        self.vlCevaplar.setObjectName("vlCevaplar")
        self.cevapAnahtari = QtWidgets.QHBoxLayout()
        self.cevapAnahtari.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.cevapAnahtari.setObjectName("cevapAnahtari")
        self.vlCevaplar.addLayout(self.cevapAnahtari)
        self.ogrenciCevaplar = QtWidgets.QHBoxLayout()
        self.ogrenciCevaplar.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.ogrenciCevaplar.setObjectName("ogrenciCevaplar")
        self.vlCevaplar.addLayout(self.ogrenciCevaplar)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.startCam.setText(_translate("Dialog", " Duraklat"))
        self.btnOtomatikDurdur.setText(_translate("Dialog", " Otomatik Durdur \n"
"        Kapalı"))
        self.btnAsamalar.setText(_translate("Dialog", " Aşamaları Göster "))
        self.btnAyarlar.setText(_translate("Dialog", "  Ayarları Aç"))
        self.btnKopyala.setText(_translate("Dialog", "  Kopyala"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
